name: pr
  
on:
  pull_request:
    branches:
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: xianfengyuan/webapp:${{ github.event.pull_request.head.sha }}
  update-image-tag-in-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          echo "cloning app repo"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/argocd-course-webapp.git
          cd argocd-course-webapp
          echo "checkout source branch"
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "updating image tag in values file"
          sed -i "s,tag:.*,tag:\ ${{ github.event.pull_request.head.sha }}," helm/webapp/values.yaml
          git add . && git commit -m "update image tag [skip ci]"
          git push
  add_labels:
    runs-on: ubuntu-latest
    needs: update-image-tag-in-helm
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            preview



